"""multi agent assistant

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-11 05:29:32.278101
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ASSISTANT_TABLES = (
    "assistant_conversations",
    "assistant_messages",
    "assistant_turns",
    "orchestration_runs",
    "agent_runs",
    "agent_handoffs",
    "agent_checkpoints",
    "agent_context_references",
    "skill_invocations",
    "tool_invocations",
    "agent_model_invocations",
    "assistant_events",
    "assistant_jobs",
)


def _enable_rls(table_name: str, predicate: str) -> None:
    op.execute(sa.text(f'ALTER TABLE "{table_name}" ENABLE ROW LEVEL SECURITY'))
    op.execute(sa.text(f'ALTER TABLE "{table_name}" FORCE ROW LEVEL SECURITY'))
    op.execute(
        sa.text(
            f'CREATE POLICY "{table_name}_tenant_owner" ON "{table_name}" '
            f"USING ({predicate}) WITH CHECK ({predicate})"
        )
    )


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistant_conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("owner_membership_id", sa.Uuid(), nullable=False),
        sa.Column("locale", sa.String(length=2), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="ACTIVE", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("last_message_sequence", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_event_sequence", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "locale IN ('vi', 'en')", name=op.f("ck_assistant_conversations_locale")
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'ARCHIVED')", name=op.f("ck_assistant_conversations_status")
        ),
        sa.CheckConstraint(
            "last_event_sequence >= 0", name=op.f("ck_assistant_conversations_event_sequence")
        ),
        sa.CheckConstraint(
            "last_message_sequence >= 0", name=op.f("ck_assistant_conversations_message_sequence")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_assistant_conversations_version")),
        sa.ForeignKeyConstraint(
            ["organization_id", "owner_membership_id"],
            ["memberships.organization_id", "memberships.id"],
            name=op.f("fk_assistant_conversations_organization_id_owner_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_conversations")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_assistant_conversations_organization_id_id")
        ),
    )
    op.create_index(
        "ix_assistant_conversations_owner_timeline",
        "assistant_conversations",
        ["organization_id", "owner_membership_id", "updated_at", "id"],
        unique=False,
    )
    op.create_table(
        "assistant_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content_blocks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_membership_id", sa.Uuid(), nullable=True),
        sa.Column("turn_id", sa.Uuid(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('USER', 'ASSISTANT', 'SYSTEM')", name=op.f("ck_assistant_messages_role")
        ),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_assistant_messages_sequence")),
        sa.ForeignKeyConstraint(
            ["organization_id", "conversation_id"],
            ["assistant_conversations.organization_id", "assistant_conversations.id"],
            name=op.f(
                "fk_assistant_messages_organization_id_conversation_id_assistant_conversations"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "created_by_membership_id"],
            ["memberships.organization_id", "memberships.id"],
            name=op.f("fk_assistant_messages_organization_id_created_by_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "turn_id"],
            ["assistant_turns.organization_id", "assistant_turns.id"],
            name="fk_assistant_messages_turn",
            ondelete="SET NULL",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_messages")),
        sa.UniqueConstraint(
            "organization_id",
            "conversation_id",
            "dedupe_key",
            name=op.f("uq_assistant_messages_organization_id_conversation_id_dedupe_key"),
        ),
        sa.UniqueConstraint(
            "organization_id",
            "conversation_id",
            "sequence",
            name=op.f("uq_assistant_messages_organization_id_conversation_id_sequence"),
        ),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_assistant_messages_organization_id_id")
        ),
    )
    op.create_index(
        "ix_assistant_messages_timeline",
        "assistant_messages",
        ["organization_id", "conversation_id", "sequence"],
        unique=False,
    )
    op.create_table(
        "assistant_turns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("user_message_id", sa.Uuid(), nullable=False),
        sa.Column("actor_membership_id", sa.Uuid(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("locale", sa.String(length=2), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="QUEUED", nullable=False),
        sa.Column("safe_error_code", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("locale IN ('vi', 'en')", name=op.f("ck_assistant_turns_locale")),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'RUNNING', 'AWAITING_INPUT', 'AWAITING_HUMAN', "
            "'COMPLETED', 'FAILED')",
            name=op.f("ck_assistant_turns_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "actor_membership_id"],
            ["memberships.organization_id", "memberships.id"],
            name=op.f("fk_assistant_turns_organization_id_actor_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "conversation_id"],
            ["assistant_conversations.organization_id", "assistant_conversations.id"],
            name=op.f("fk_assistant_turns_organization_id_conversation_id_assistant_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "user_message_id"],
            ["assistant_messages.organization_id", "assistant_messages.id"],
            name=op.f("fk_assistant_turns_organization_id_user_message_id_assistant_messages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_turns")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_assistant_turns_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "user_message_id",
            name=op.f("uq_assistant_turns_organization_id_user_message_id"),
        ),
    )
    op.create_index(
        "ix_assistant_turns_conversation",
        "assistant_turns",
        ["organization_id", "conversation_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "orchestration_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("turn_id", sa.Uuid(), nullable=False),
        sa.Column("orchestrator_version", sa.String(length=64), nullable=False),
        sa.Column("orchestrator_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("execution_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "checkpoint",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("budget", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "usage",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=30), server_default="QUEUED", nullable=False),
        sa.Column("stop_reason", sa.String(length=100), nullable=True),
        sa.Column("safe_error_code", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'RUNNING', 'AWAITING_INPUT', 'AWAITING_HUMAN', "
            "'COMPLETED', 'FAILED')",
            name=op.f("ck_orchestration_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "turn_id"],
            ["assistant_turns.organization_id", "assistant_turns.id"],
            name=op.f("fk_orchestration_runs_organization_id_turn_id_assistant_turns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orchestration_runs")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_orchestration_runs_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id", "turn_id", name=op.f("uq_orchestration_runs_organization_id_turn_id")
        ),
    )
    op.create_index(
        "ix_orchestration_runs_status",
        "orchestration_runs",
        ["organization_id", "status", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("orchestration_run_id", sa.Uuid(), nullable=False),
        sa.Column("parent_agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("inbound_handoff_id", sa.Uuid(), nullable=True),
        sa.Column("agent_id", sa.String(length=100), nullable=False),
        sa.Column("agent_version", sa.String(length=64), nullable=False),
        sa.Column("manifest_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("capability", sa.String(length=100), nullable=False),
        sa.Column("typed_input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("typed_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "version_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("budget", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "usage",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=30), server_default="QUEUED", nullable=False),
        sa.Column("stop_reason", sa.String(length=100), nullable=True),
        sa.Column("safe_error_code", sa.String(length=100), nullable=True),
        sa.Column("workflow_run_id", sa.Uuid(), nullable=True),
        sa.Column("projected_workflow_sequence", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'RUNNING', 'AWAITING_INPUT', 'AWAITING_HUMAN', "
            "'COMPLETED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_agent_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "inbound_handoff_id"],
            ["agent_handoffs.organization_id", "agent_handoffs.id"],
            name="fk_agent_runs_inbound_handoff",
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "orchestration_run_id"],
            ["orchestration_runs.organization_id", "orchestration_runs.id"],
            name=op.f("fk_agent_runs_organization_id_orchestration_run_id_orchestration_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "parent_agent_run_id"],
            ["agent_runs.organization_id", "agent_runs.id"],
            name=op.f("fk_agent_runs_organization_id_parent_agent_run_id_agent_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workflow_run_id"],
            ["workflow_runs.organization_id", "workflow_runs.id"],
            name=op.f("fk_agent_runs_organization_id_workflow_run_id_workflow_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_agent_runs_organization_id_id")),
    )
    op.create_index(
        "ix_agent_runs_orchestration",
        "agent_runs",
        ["organization_id", "orchestration_run_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_agent_runs_workflow",
        "agent_runs",
        ["organization_id", "workflow_run_id", "id"],
        unique=False,
    )
    op.create_table(
        "assistant_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("turn_id", sa.Uuid(), nullable=False),
        sa.Column("orchestration_run_id", sa.Uuid(), nullable=False),
        sa.Column("requester_membership_id", sa.Uuid(), nullable=False),
        sa.Column(
            "job_type",
            sa.String(length=100),
            server_default="assistant.turn.execute",
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="QUEUED", nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("locked_by", sa.String(length=255), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("safe_error_code", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "job_type = 'assistant.turn.execute'", name=op.f("ck_assistant_jobs_job_type")
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED')",
            name=op.f("ck_assistant_jobs_status"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0 AND attempt_count <= max_attempts",
            name=op.f("ck_assistant_jobs_attempts"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "conversation_id"],
            ["assistant_conversations.organization_id", "assistant_conversations.id"],
            name=op.f("fk_assistant_jobs_organization_id_conversation_id_assistant_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "orchestration_run_id"],
            ["orchestration_runs.organization_id", "orchestration_runs.id"],
            name=op.f("fk_assistant_jobs_organization_id_orchestration_run_id_orchestration_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "requester_membership_id"],
            ["memberships.organization_id", "memberships.id"],
            name=op.f("fk_assistant_jobs_organization_id_requester_membership_id_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "turn_id"],
            ["assistant_turns.organization_id", "assistant_turns.id"],
            name=op.f("fk_assistant_jobs_organization_id_turn_id_assistant_turns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_jobs")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_assistant_jobs_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "orchestration_run_id",
            "job_type",
            name=op.f("uq_assistant_jobs_organization_id_orchestration_run_id_job_type"),
        ),
    )
    op.create_index(
        "ix_assistant_jobs_lease",
        "assistant_jobs",
        ["organization_id", "locked_by", "lease_until", "id"],
        unique=False,
    )
    op.create_index(
        "ix_assistant_jobs_queue",
        "assistant_jobs",
        ["organization_id", "status", "available_at", "lease_until", "id"],
        unique=False,
    )
    op.create_table(
        "agent_checkpoints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("orchestration_run_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("node", sa.String(length=100), nullable=False),
        sa.Column("typed_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checkpoint_version", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "agent_run_id"],
            ["agent_runs.organization_id", "agent_runs.id"],
            name=op.f("fk_agent_checkpoints_organization_id_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "orchestration_run_id"],
            ["orchestration_runs.organization_id", "orchestration_runs.id"],
            name=op.f(
                "fk_agent_checkpoints_organization_id_orchestration_run_id_orchestration_runs"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_checkpoints")),
        sa.UniqueConstraint(
            "organization_id",
            "agent_run_id",
            "sequence",
            name=op.f("uq_agent_checkpoints_organization_id_agent_run_id_sequence"),
        ),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_agent_checkpoints_organization_id_id")
        ),
    )
    op.create_index(
        "ix_agent_checkpoints_run",
        "agent_checkpoints",
        ["organization_id", "agent_run_id", "sequence"],
        unique=False,
    )
    op.create_table(
        "agent_context_references",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("resource_version", sa.Integer(), nullable=True),
        sa.Column("fingerprint", sa.String(length=128), nullable=True),
        sa.Column("permission_scope", sa.String(length=100), nullable=False),
        sa.Column("freshness_required", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "agent_run_id"],
            ["agent_runs.organization_id", "agent_runs.id"],
            name=op.f("fk_agent_context_references_organization_id_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_context_references")),
        sa.UniqueConstraint(
            "organization_id",
            "agent_run_id",
            "resource_type",
            "resource_id",
            name=op.f(
                "uq_agent_context_references_organization_id_agent_run_id_resource_type_resource_id"
            ),
        ),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_agent_context_references_organization_id_id")
        ),
    )
    op.create_index(
        "ix_agent_context_references_run",
        "agent_context_references",
        ["organization_id", "agent_run_id", "id"],
        unique=False,
    )
    op.create_table(
        "agent_handoffs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("orchestration_run_id", sa.Uuid(), nullable=False),
        sa.Column("parent_agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("target_agent_id", sa.String(length=100), nullable=False),
        sa.Column("target_agent_version", sa.String(length=64), nullable=False),
        sa.Column("capability", sa.String(length=100), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("typed_input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("context_references", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("budget", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("step_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "orchestration_run_id"],
            ["orchestration_runs.organization_id", "orchestration_runs.id"],
            name=op.f("fk_agent_handoffs_organization_id_orchestration_run_id_orchestration_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "parent_agent_run_id"],
            ["agent_runs.organization_id", "agent_runs.id"],
            name=op.f("fk_agent_handoffs_organization_id_parent_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_handoffs")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_agent_handoffs_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "orchestration_run_id",
            "dedupe_key",
            name=op.f("uq_agent_handoffs_organization_id_orchestration_run_id_dedupe_key"),
        ),
    )
    op.create_index(
        "ix_agent_handoffs_parent",
        "agent_handoffs",
        ["organization_id", "parent_agent_run_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "agent_model_invocations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("invocation_key", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("safe_error_code", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('SUCCEEDED', 'REJECTED', 'FAILED')",
            name=op.f("ck_agent_model_invocations_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "agent_run_id"],
            ["agent_runs.organization_id", "agent_runs.id"],
            name=op.f("fk_agent_model_invocations_organization_id_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_model_invocations")),
        sa.UniqueConstraint(
            "organization_id",
            "agent_run_id",
            "invocation_key",
            name=op.f("uq_agent_model_invocations_organization_id_agent_run_id_invocation_key"),
        ),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_agent_model_invocations_organization_id_id")
        ),
    )
    op.create_index(
        "ix_agent_model_invocations_run",
        "agent_model_invocations",
        ["organization_id", "agent_run_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "assistant_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("public_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("turn_id", sa.Uuid(), nullable=True),
        sa.Column("orchestration_run_id", sa.Uuid(), nullable=True),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("source_type", sa.String(length=100), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("source_sequence", sa.Integer(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=255), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_assistant_events_sequence")),
        sa.ForeignKeyConstraint(
            ["organization_id", "agent_run_id"],
            ["agent_runs.organization_id", "agent_runs.id"],
            name=op.f("fk_assistant_events_organization_id_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "conversation_id"],
            ["assistant_conversations.organization_id", "assistant_conversations.id"],
            name=op.f(
                "fk_assistant_events_organization_id_conversation_id_assistant_conversations"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "orchestration_run_id"],
            ["orchestration_runs.organization_id", "orchestration_runs.id"],
            name=op.f(
                "fk_assistant_events_organization_id_orchestration_run_id_orchestration_runs"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "turn_id"],
            ["assistant_turns.organization_id", "assistant_turns.id"],
            name=op.f("fk_assistant_events_organization_id_turn_id_assistant_turns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_events")),
        sa.UniqueConstraint(
            "organization_id",
            "conversation_id",
            "dedupe_key",
            name=op.f("uq_assistant_events_organization_id_conversation_id_dedupe_key"),
        ),
        sa.UniqueConstraint(
            "organization_id",
            "conversation_id",
            "sequence",
            name=op.f("uq_assistant_events_organization_id_conversation_id_sequence"),
        ),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_assistant_events_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "source_type",
            "source_id",
            "source_sequence",
            name=op.f("uq_assistant_events_organization_id_source_type_source_id_source_sequence"),
        ),
    )
    op.create_index(
        "ix_assistant_events_replay",
        "assistant_events",
        ["organization_id", "conversation_id", "sequence"],
        unique=False,
    )
    op.create_table(
        "skill_invocations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.String(length=100), nullable=False),
        sa.Column("skill_version", sa.String(length=64), nullable=False),
        sa.Column("typed_input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("typed_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="RUNNING", nullable=False),
        sa.Column("safe_error_code", sa.String(length=100), nullable=True),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('RUNNING', 'SUCCEEDED', 'REJECTED', 'FAILED')",
            name=op.f("ck_skill_invocations_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "agent_run_id"],
            ["agent_runs.organization_id", "agent_runs.id"],
            name=op.f("fk_skill_invocations_organization_id_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_invocations")),
        sa.UniqueConstraint(
            "organization_id",
            "agent_run_id",
            "dedupe_key",
            name=op.f("uq_skill_invocations_organization_id_agent_run_id_dedupe_key"),
        ),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_skill_invocations_organization_id_id")
        ),
    )
    op.create_index(
        "ix_skill_invocations_run",
        "skill_invocations",
        ["organization_id", "agent_run_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "tool_invocations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("tool_id", sa.String(length=100), nullable=False),
        sa.Column("tool_version", sa.String(length=64), nullable=False),
        sa.Column("risk_level", sa.String(length=30), nullable=False),
        sa.Column("typed_input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("typed_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("context_references", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="RUNNING", nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column("safe_error_code", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('RUNNING', 'SUCCEEDED', 'REJECTED', 'FAILED')",
            name=op.f("ck_tool_invocations_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "agent_run_id"],
            ["agent_runs.organization_id", "agent_runs.id"],
            name=op.f("fk_tool_invocations_organization_id_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_invocations")),
        sa.UniqueConstraint(
            "organization_id",
            "agent_run_id",
            "dedupe_key",
            name=op.f("uq_tool_invocations_organization_id_agent_run_id_dedupe_key"),
        ),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_tool_invocations_organization_id_id")
        ),
    )
    op.create_index(
        "ix_tool_invocations_run",
        "tool_invocations",
        ["organization_id", "agent_run_id", "created_at", "id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_assistant_messages_turn",
        "assistant_messages",
        "assistant_turns",
        ["organization_id", "turn_id"],
        ["organization_id", "id"],
        ondelete="SET NULL",
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_agent_runs_inbound_handoff",
        "agent_runs",
        "agent_handoffs",
        ["organization_id", "inbound_handoff_id"],
        ["organization_id", "id"],
        ondelete="RESTRICT",
    )

    owner_setting = (
        "organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid "
        "AND (NULLIF(current_setting('app.membership_id', true), '') IS NULL OR "
        "owner_membership_id = "
        "NULLIF(current_setting('app.membership_id', true), '')::uuid)"
    )
    orchestration_owner = (
        "orchestration_runs.organization_id = "
        "NULLIF(current_setting('app.organization_id', true), '')::uuid "
        "AND EXISTS (SELECT 1 FROM assistant_turns t "
        "WHERE t.organization_id = orchestration_runs.organization_id "
        "AND t.id = orchestration_runs.turn_id)"
    )
    agent_owner = (
        "agent_runs.organization_id = "
        "NULLIF(current_setting('app.organization_id', true), '')::uuid "
        "AND EXISTS (SELECT 1 FROM orchestration_runs r "
        "WHERE r.organization_id = agent_runs.organization_id "
        "AND r.id = agent_runs.orchestration_run_id)"
    )
    _enable_rls("assistant_conversations", owner_setting)
    for table_name in ("assistant_messages", "assistant_turns", "assistant_events"):
        _enable_rls(
            table_name,
            f"{table_name}.organization_id = "
            "NULLIF(current_setting('app.organization_id', true), '')::uuid "
            "AND EXISTS (SELECT 1 FROM assistant_conversations c "
            f"WHERE c.organization_id = {table_name}.organization_id "
            f"AND c.id = {table_name}.conversation_id)",
        )
    _enable_rls("orchestration_runs", orchestration_owner)
    _enable_rls("agent_runs", agent_owner)
    _enable_rls(
        "agent_handoffs",
        "agent_handoffs.organization_id = "
        "NULLIF(current_setting('app.organization_id', true), '')::uuid "
        "AND EXISTS (SELECT 1 FROM agent_runs a "
        "WHERE a.organization_id = agent_handoffs.organization_id "
        "AND a.id = agent_handoffs.parent_agent_run_id)",
    )
    _enable_rls(
        "agent_checkpoints",
        "agent_checkpoints.organization_id = "
        "NULLIF(current_setting('app.organization_id', true), '')::uuid "
        "AND EXISTS (SELECT 1 FROM agent_runs a "
        "WHERE a.organization_id = agent_checkpoints.organization_id "
        "AND a.id = agent_checkpoints.agent_run_id)",
    )
    for table_name in (
        "agent_context_references",
        "skill_invocations",
        "tool_invocations",
        "agent_model_invocations",
    ):
        _enable_rls(
            table_name,
            f"{table_name}.organization_id = "
            "NULLIF(current_setting('app.organization_id', true), '')::uuid "
            "AND EXISTS (SELECT 1 FROM agent_runs a "
            f"WHERE a.organization_id = {table_name}.organization_id "
            f"AND a.id = {table_name}.agent_run_id)",
        )
    _enable_rls(
        "assistant_jobs",
        "assistant_jobs.organization_id = "
        "NULLIF(current_setting('app.organization_id', true), '')::uuid "
        "AND (NULLIF(current_setting('app.membership_id', true), '') IS NULL OR "
        "EXISTS (SELECT 1 FROM assistant_conversations c "
        "WHERE c.organization_id = assistant_jobs.organization_id "
        "AND c.id = assistant_jobs.conversation_id))",
    )

    op.execute(
        """
        CREATE FUNCTION protect_assistant_invocation_terminal()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF OLD.status <> 'RUNNING' THEN
                RAISE EXCEPTION 'assistant invocation is already terminal';
            END IF;
            IF NEW.status = 'RUNNING' THEN
                RAISE EXCEPTION 'assistant invocation terminal update required';
            END IF;
            IF (to_jsonb(NEW) - ARRAY['typed_output', 'status', 'safe_error_code', 'completed_at'])
               IS DISTINCT FROM
               (to_jsonb(OLD) - ARRAY['typed_output', 'status', 'safe_error_code', 'completed_at'])
            THEN
                RAISE EXCEPTION 'assistant invocation identity and input are immutable';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER protect_skill_invocation_terminal BEFORE UPDATE ON skill_invocations "
        "FOR EACH ROW EXECUTE FUNCTION protect_assistant_invocation_terminal()"
    )
    op.execute(
        "CREATE TRIGGER protect_tool_invocation_terminal BEFORE UPDATE ON tool_invocations "
        "FOR EACH ROW EXECUTE FUNCTION protect_assistant_invocation_terminal()"
    )

    for table_name in ASSISTANT_TABLES:
        op.execute(sa.text(f'ALTER TABLE "{table_name}" OWNER TO migration_owner'))
        op.execute(sa.text(f'REVOKE ALL ON "{table_name}" FROM app_runtime'))
        op.execute(sa.text(f'GRANT SELECT, INSERT ON "{table_name}" TO app_runtime'))
        op.execute(sa.text(f'REVOKE UPDATE, DELETE ON "{table_name}" FROM app_runtime'))

    update_columns = {
        "assistant_conversations": (
            "title, status, version, last_message_sequence, last_event_sequence, updated_at"
        ),
        "assistant_turns": "status, safe_error_code, updated_at",
        "orchestration_runs": (
            "execution_plan, checkpoint, usage, status, stop_reason, safe_error_code, "
            "started_at, completed_at, updated_at"
        ),
        "agent_runs": (
            "typed_output, version_metadata, usage, status, stop_reason, safe_error_code, "
            "workflow_run_id, projected_workflow_sequence, started_at, completed_at, updated_at"
        ),
        "assistant_jobs": (
            "status, attempt_count, available_at, locked_by, lease_until, "
            "safe_error_code, updated_at"
        ),
        "skill_invocations": "typed_output, status, safe_error_code, completed_at",
        "tool_invocations": "typed_output, status, safe_error_code, completed_at",
    }
    for table_name, columns in update_columns.items():
        op.execute(sa.text(f'GRANT UPDATE ({columns}) ON "{table_name}" TO app_runtime'))

    op.execute("ALTER FUNCTION protect_assistant_invocation_terminal() OWNER TO migration_owner")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when the revision supports it."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_agent_runs_inbound_handoff", "agent_runs", type_="foreignkey")
    op.drop_constraint("fk_assistant_messages_turn", "assistant_messages", type_="foreignkey")
    op.execute("DROP FUNCTION protect_assistant_invocation_terminal() CASCADE")
    op.drop_index("ix_tool_invocations_run", table_name="tool_invocations")
    op.drop_table("tool_invocations")
    op.drop_index("ix_skill_invocations_run", table_name="skill_invocations")
    op.drop_table("skill_invocations")
    op.drop_index("ix_assistant_events_replay", table_name="assistant_events")
    op.drop_table("assistant_events")
    op.drop_index("ix_agent_model_invocations_run", table_name="agent_model_invocations")
    op.drop_table("agent_model_invocations")
    op.drop_index("ix_agent_handoffs_parent", table_name="agent_handoffs")
    op.drop_table("agent_handoffs")
    op.drop_index("ix_agent_context_references_run", table_name="agent_context_references")
    op.drop_table("agent_context_references")
    op.drop_index("ix_agent_checkpoints_run", table_name="agent_checkpoints")
    op.drop_table("agent_checkpoints")
    op.drop_index("ix_assistant_jobs_queue", table_name="assistant_jobs")
    op.drop_index("ix_assistant_jobs_lease", table_name="assistant_jobs")
    op.drop_table("assistant_jobs")
    op.drop_index("ix_agent_runs_workflow", table_name="agent_runs")
    op.drop_index("ix_agent_runs_orchestration", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index("ix_orchestration_runs_status", table_name="orchestration_runs")
    op.drop_table("orchestration_runs")
    op.drop_index("ix_assistant_turns_conversation", table_name="assistant_turns")
    op.drop_table("assistant_turns")
    op.drop_index("ix_assistant_messages_timeline", table_name="assistant_messages")
    op.drop_table("assistant_messages")
    op.drop_index("ix_assistant_conversations_owner_timeline", table_name="assistant_conversations")
    op.drop_table("assistant_conversations")
    # ### end Alembic commands ###
